# GSOF 49

std_msgs/Header header
GpsTimeGsof gps_time
StatusGsof status
LLA lla
NED velocity                                    # meters / second
float32 total_speed                             # meters / second
float64 roll                                    # degrees
float64 pitch                                   # degrees
float64 heading                                 # degrees
float64 track_angle                             # degrees
float32 ang_rate_long                           # degrees / second
float32 ang_rate_trans                          # degrees / second
float32 ang_rate_down                           # degrees / second
float32 acc_long                                # meters / second^2
float32 acc_trans                               # meters / second^2
float32 acc_down                                # meters / second^2
